version: "3"

services:
  
  postgres_db:
    container_name: ${DOCKER_CONTAINER_DB_NAME}
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    restart: no
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db/cached-db-data/postgres/:/var/lib/postgresql/data/

