name: Deploy Go binary to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build Go binary
        run: go build -o main

      - name: Deploy Go binary to AWS EC2
        uses: aws-actions/aws-cli@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          s3-bucket: my-bucket
          s3-key: main
          ec2-instance-id: i-1234567890abcdef0

      - name: Run Go binary on AWS EC2
        run: ssh ubuntu@${{ secrets.EC2_HOSTNAME }} "sudo ./main"
