DROP TABLE IF EXISTS users     CASCADE;
DROP TABLE IF EXISTS meetings  CASCADE;
DROP TABLE IF EXISTS subjects  CASCADE;
DROP TABLE IF EXISTS teachings CASCADE;
DROP TABLE IF EXISTS bills     CASCADE;

